version = 0.1

[default.deploy.parameters]
stack_name = "english-learning-mcp"
resolve_s3 = true
s3_prefix = "english-learning-mcp"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DefaultUserId=\"default_user\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
